### ISSUE TITLE
Displaying party members on world map

### ISSUE THREAD

**Issue by Maskloss** [NeverScapeAlone/never-scape-alone#112]
Relates to #103 but having a display of where a party member is on the world map would be quite handy. Especially if there are any players in the group who are new to oldschool runescape and dont know where you ( the experienced player) are when you say that you are 'at north side of the ge' or when you want to know where they are but the best they can do is say ' im at draynor village' when actually they are roughly 2 tiles out from being in falador.

Would be probably feature creep but having a toggle for showing a relatively small area of the map next to them in the on-screen UI. Perhaps with an option for how frequent to update the little map segment. 
Essentially the player who you are observing on this minimap would be a coloured dot on an actual minimap display or the likely easier implementation of a small minimap sized portion of the world map showing the general area around them. 

![image](https://user-images.githubusercontent.com/110988819/183982055-7b0cb18f-84e9-4969-b6f1-d7ed2ab77e95.png)
If you are able to show a minimap like this ^ but with semi frequent updating. Would be neat. Or as a toggle perhaps.
If not then something a little more generic and semi static like the image below. But with the giant YOU ARE HERE shaped X that the ingame map currently has. Color coded would be cool too.
![image](https://user-images.githubusercontent.com/110988819/183982690-65fd64fc-1835-4a05-b938-47b1012b3ea4.png)

Or just a big fat X on the ingame map for where each party member is located. Of course as a toggle per player.

Not sure if i made it clear as its 4am when i am writing this but i hope it makes some kind of sense

**Comment by Ferrariic** [comment]
This is a perfectly done issue, and should be very possible considering that I currently send location pings every 10 seconds. 

Effectively I'll need to draw those two locations from the input location data. Should be doable.

**Comment by Maskloss** [comment]
And i guess if someone wants to be all anti social and not share their location then an option for that should be available for them too.

**Comment by Sprinkles-GS** [comment]
[Related- sub Issue](https://github.com/NeverScapeAlone/never-scape-alone/issues/124)
