### ISSUE TITLE
Group Full - Stops connecting.

### ISSUE THREAD

**Issue by ItsRedRing** [NeverScapeAlone/never-scape-alone#113]
**Describe the bug**
When there are only full groups in the que you will get the message Group Full, but reconnecting keeps counting up as if you were in que still for an open group, which is false.

**To Reproduce**
1. Have all groups in que be full.
2. Try to connect through random activity
3. Yellow text ontop should say "Group Full" with the connecting...que time still counting up.
4. Attached picture link example - https://prnt.sc/BzBZFBnCRTT6

**Expected behavior**
The page to change notifing me their is no avaliable groups to join and the connecting timer would stop.

**Screenshots**
(https://prnt.sc/BzBZFBnCRTT6)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera GX
 - Version: Yea, I'm not to sure.

**Additional context**
This project is awesome!

**Comment by Ferrariic** [comment]
Thank you for the excellent issue!
