### ISSUE TITLE
Opt out

### ISSUE THREAD

**Issue by extreme4all** [NeverScapeAlone/never-scape-alone#202]
**Is your feature request related to a problem? Please describe.**
I don't want people to know anything about me, unless i opt-in.

**Describe the solution you'd like**
Default opt-out, opt-in an option

**Comment by Ferrariic** [comment]
You opt in by installing the plugin. I'll include this warning in the plugin installation.

**Comment by extreme4all** [comment]
> You opt in by installing the plugin. I'll include this warning in the plugin installation.

Well, this is very limiting, what if i want to use the grouping but not want to share my location, run energy, hp, etc with the group

**Comment by Ferrariic** [comment]
> > You opt in by installing the plugin. I'll include this warning in the plugin installation.
> 
> Well, this is very limiting, what if i want to use the grouping but not want to share my location, run energy, hp, etc with the group

I've given this some thought, and tbh if they don't want all of those features -- then they can just not install the plugin. I don't have any plans on adding opt-out features. It doesn't make sense to work around it on my end for a relatively small number of players. 

They opt-in currently on two occasions:
1. Installing the plugin
2. Joining a private or public group.

I don't see relevancy for including an opt-out feature when that defeats one of the main points of the plugin.

**Comment by Ferrariic** [comment]
This will be added with runeguard.
