### ISSUE TITLE
Convert to WebSocket for v2.0.0-alpha

### ISSUE THREAD

**Issue by Ferrariic** [NeverScapeAlone/never-scape-alone#27]
Replace standalone HTTP with Websocket where possible.

**Comment by Tyluur** [comment]
KTor would be a good library to implement WebSockets with.
See URL: [[https://ktor.io/docs/websocket.html#configure](https://ktor.io/docs/websocket.html#configure)]

**Comment by Ferrariic** [comment]
Good advice, thank you! I'll consider it :)
